### ISSUE TITLE
Usage of this engine

### ISSUE THREAD

**Issue by chadvincula** [FireFox2000000/GbaGameEngine#1]
Hello!

My name is Charles Advincula and I am a game design student at UC Santa Cruz. My group was working on a GBA game for our senior capstone, but our engine has been failing us, unfortunately. We are hoping we may switch to this engine as well as gain some insight from you as to how we can use this engine to create GBA games such as creating scenes, putting sprites on the screen, getting animation to work, etc. I understand that this is out-of-the-blue, but it would be great if you can reach out as soon as possible. My email is cadvincu@ucsc.edu and I look forward to hearing from you soon!

Sincerely,

Charles Advincula
CS: Computer Game Design Undergraduate
UC Santa Cruz

**Comment by FireFox2000000** [comment]
Hi Charles! 

Sorry for not seeing this sooner, wasn't expecting this repo to gain any kind of attention. 
This is a very work-in-progress engine and has a lot of missing features and issues with it at the moment. This is very much just a hobby project of mine so I'd advise strong caution if you are planning to use it for anything other than a super small demo if I'm honest.

Currently it's only really capable of sprite/animation rendering, very inefficient font rendering (currently uses individual sprites instead of a single tilemap for characters) and background rendering that is limited to 512x512 pixels, ala no Pokemon esq. level design etc. The backgrounds themselves also don't unload properly, which is due to the hacky nature I was doing things in to get it ready of a game jam I was participating in. I have a plan to fix up the backgrounds and make them way more flexible but at the moment currently haven't had time to get around to it. 

The last few major updates I was putting stuff together to test this engine for a game jam. You can take a look at what it's currently capable of my playing the game we made here-
https://itch.io/jam/touhou-jam-5/rate/552036
The branch that game was made on can also be found here-
https://github.com/FireFox2000000/GbaGameEngine/tree/touhou_fan_game_jam_5

That being said, tons of key features are missing like sound, rotatable/scalable sprites, physics, tilemap font/ui system, object parenting, GBA specific graphic effects etc etc. Setting up scenes is also done completely in code with no modern level editing or anything, though I wasn't really planning that to begin with. There's also no documentation as again, this was purely a hobby project of mine and there are no guarantees of support by me on this engine.
It's an extremely limited engine at the moment, so depending on your scope and how skilled at programming your team is, it may not be feasible to use and I honestly wouldn't really recommend it unless you have no other option. 

If you are still interested in using it then I'd be happy to provide a basic overview and point you in the right direction to help fill in the holes, but I won't be able to provide you much more than light question answering due to the limited time I have focusing on other projects for the moment. If not, I'm thankful for you reaching out and checking out this little project I've put together anyway.
